spring:
  application:
    name: cloud-provider

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8080/eureka/   #服务注册中信地址，含有BASIC认证的用户名和密码
    register-with-eureka: false
  instance:
    #将IP注册到服务注册中心
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4

